// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf1AOW4ozUfnEUjKc6YKVgKDyNolUpM0U',
    appId: '1:43702926796:web:dcce7d98c866e4167e7169',
    messagingSenderId: '43702926796',
    projectId: 'e-commerce-2f411',
    authDomain: 'e-commerce-2f411.firebaseapp.com',
    storageBucket: 'e-commerce-2f411.appspot.com',
    measurementId: 'G-6GTRXHHSLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCudktaqMju7As7cuwU95S0HVlM8ZI5JAM',
    appId: '1:43702926796:android:6fb6a780614159c27e7169',
    messagingSenderId: '43702926796',
    projectId: 'e-commerce-2f411',
    storageBucket: 'e-commerce-2f411.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvNnSdaN8-zAo-AxXCxW0-Ejm9w6F0Ago',
    appId: '1:43702926796:ios:626c3f39e61e0ebe7e7169',
    messagingSenderId: '43702926796',
    projectId: 'e-commerce-2f411',
    storageBucket: 'e-commerce-2f411.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvNnSdaN8-zAo-AxXCxW0-Ejm9w6F0Ago',
    appId: '1:43702926796:ios:eff68203b79f33ae7e7169',
    messagingSenderId: '43702926796',
    projectId: 'e-commerce-2f411',
    storageBucket: 'e-commerce-2f411.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
